name: test_utils
description: A test utils bundle written by @mitryp to be used in his packages.
version: 0.0.2
repository: https://github.com/mitryp/flutter_utils/tree/master/packages/test_utils

environment:
  sdk: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
