import 'dart:math';

import 'package:date_time_utils/time_of_day_utils.dart';
import 'package:flutter/material.dart' show TimeOfDay;

/// A maximum amount of minutes per day.
const maxMinutes = TimeOfDay.hoursPerDay * TimeOfDay.minutesPerHour;

/// Maximum value generated by [Random.nextInt].
const maxRandom = 2 << 31;

/// Returns a random integer between 0 (inclusive) and [_maxMinutes] (exclusive).
int randomMinutes(Random random) => random.nextInt(maxMinutes);

/// Returns a random valid [TimeOfDay].
TimeOfDay randomTime(Random random) => timeFromMinutes(randomMinutes(random));

/// Returns a random valid timestamp in the past.
int randomTimestamp(Random random) => random.nextInt(maxRandom) * 100;
